name: '${project.name}'
version: '${project.version}'
main: me.sora819.specialitems.SpecialItems
api-version: '1.21'
author: 'Sora819'

commands:
  specialItems:
    usage: '/<command> <subcommand> [<parameters>]'
    aliases:
      - speciali
      - si